[database]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "doraemon"

[auth]
cypher_key = "example_key"
token_lifetime = 3600
auth_code_lifetime = 600

[url]
client_secret = "no-secret"
